### ISSUE TITLE
SGM as pandas

### ISSUE THREAD

**Issue by alvations** [mjpost/sacreBLEU#1]
Wouldn't it be simpler if every evaluation SGM and submission becomes a `pandas` dataframe? https://github.com/alvations/warmth/blob/master/wmt_metric_task_data_indices.py

**Comment by mjpost** [comment]
You mean, if WMT published them? What's panda? It *would* be nice to avoid listing them all out (I made two mistakes that I found later, already).

**Comment by alvations** [comment]
We re-release a version of the data that has been structured into a nice [`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) (or we can use `dask` too but it's an overkill for small dataset like the eval sets).

From previous experience, after restructuring the [STS dataset into a DataFrame](https://github.com/alvations/stasis), people really like it and the organizers was also inspired and [setup their own benchmarking (all in one place repository and tools)](http://ixa2.si.ehu.es/stswiki/index.php/STSbenchmark)

I think it's worth doing so. 

As for the listing of files. I actually printed them from `os.listdir()` after extracting but I wanted it fast so I included the list of filenames and path in python objects instead of parsing the directories each time I load the script =)

**Comment by mjpost** [comment]
I am not against this, but don't understand the advantages fully. It seems to add some complexity and dependencies without clear advantages?

**Comment by alvations** [comment]
Let me try to see whether this is possible to be hacked out over a weekend one of the November weekend ;P

**Comment by cfedermann** [comment]
A `pandas` `DataFrame` would be a nice extension, but it comes at the cost of an added dependency.

Best to add this as an optional implementation iff `pandas` is available...
@alvations: good idea to create a hacky prototype and then we can see about integration. Looking forward to seeing your code 👍

**Comment by mjpost** [comment]
Closing this for now. Feel free to reopen if it becomes relevant in the future!
