### ISSUE TITLE
Short sentence have 0 bleu

### ISSUE THREAD

**Issue by Brucewuzhang** [mjpost/sacrebleu#114]
I found that for sentences with less than 4 tokens, then bleu is always 0. Is this a bug or is it just designed to let them have 0 bleu?

**Comment by ozancaglayan** [comment]
this is probably because there are no higher order n-gram matches for those sentences, so yes it has to do with the design of BLEU and its set of default parameters.

**Comment by ozancaglayan** [comment]
Are you using sentence-bleu or the default corpus bleu by the way?

**Comment by Brucewuzhang** [comment]
> Are you using sentence-bleu or the default corpus bleu by the way?

I am using this:
from sacrebleu import corpus_bleu

**Comment by ozancaglayan** [comment]
Are all your sentences < 4 tokens in both hypotheses and references?

**Comment by mjpost** [comment]
If any of the corpus-level 1-gram, 2-gram, 3-gram, or 4-gram counts are zero, your BLEU score will be zero. If you want to avoid this, use smoothing. However, BLEU is unlikely to be useful as a metric for quality in such situations.
