### ISSUE TITLE
The input and reference stream(s) were of different lengths.

### ISSUE THREAD

**Issue by genbei** [mjpost/sacrebleu#120]
![29](https://user-images.githubusercontent.com/57440758/94507879-46462a80-0243-11eb-80ac-a1037899876f.png)
I encountered this problem in the process of using it. I won't check the format of the forecast. How should I solve this problem? Thank you very much

**Comment by ozancaglayan** [comment]
As it says in the error, it is likely that the lengths of predictions and references are not equal. If you are using sacreBLEU through another toolkit (I think that's the case), make sure you provide the correct references for evaluation. Feel free to re-open the issue and provide more detail, if the issue persists.
