### ISSUE TITLE
Versioning and compatibility

### ISSUE THREAD

**Issue by alvations** [mjpost/sacrebleu#126]
Given that the versions are changing fast, how is `sacrebleu` handling semantic versioning of `MAJOR.MINOR.PATCH`?

If the same hypotheses and references are sent to different versions of sacrebleu and reporting different numbers after a change in the version, would the MINOR / PATCH version change? 

E.g. if we use `v1.4.5` on a hyp+ref files pair and score 40 BLEU but when we use an updated version `v1.4.13` on the same files pair and score 42 BLEU, should the `v1.4.13` be instead `1.5.0`? (i.e. upgraded in the MINOR version) or should it remain as a PATCH?

**Comment by martinpopel** [comment]
Are you aware of any case where different versions of sacrebleu with the default parameters result in different results? Sacrebleu still tries to give the same results as the legacy NIST implementation, as far as I know. The differences affect mostly non-default parameters (e.g. different tokenizations, smoothings, sentence-level BLEU, addition of chrf and TER etc.).

**Comment by ozancaglayan** [comment]
From my understanding, the signatures are exactly for this kind of reproducibility, no?

**Comment by ozancaglayan** [comment]
I think the `test.sh` is exactly for this. We never update the BLEU/chrF and TER scores in that file to reflect an upcoming version. This means that we (sort of) guarantee that the outcomes of metrics with their default settings will never change across versions.

Closing this for now as no further comment received from the Op.
