### ISSUE TITLE
Inkonsistent tokenization for zh in TER and BLEU computation

### ISSUE THREAD

**Issue by e-matusov** [mjpost/sacrebleu#127]
In tokenizer_zh.py, it says: "The tokenization of Chinese text in this script contains two steps: separate each Chinese characters (by utf-8 encoding); tokenize the non Chinese part (following the `13a` i.e. mteval tokenizer)." 
However, in tokenizer_ter.py , when the option _asian_support is set (for zh it is set), it is assumed that only Asian and full-width punctuation is used in the input. This is generally not the case, even some reference files for standard test sets sometimes use ASCII full stops, and also any non-Chinese part may have ASCII punctuation.

My suggestion would be to have a common segmentaiton for Chinese/Japanese for TER, BLEU, and all the other methods to avoid such discrepancies.  In this particular case, the approach taken in tokenizer_zh.py seems to be the more consistent one.

**Comment by martinpopel** [comment]
The main question is whether we want to preserve compatibility with the TERCOM implementation of TER (by using a different tokenizer, the scores will be different). See also the discussion here https://github.com/mjpost/sacrebleu/pull/102#issuecomment-667992856

**Comment by ozancaglayan** [comment]
Although it is very appealing to merge tokenizers from different metrics and make them available to arbitrary metrics, this probably goes against the rationale of sacreBLEU which is all about providing reference implementations of metrics.

If there's a confusion as to what has been described in `tokenizer_zh.py`, that should be OK to discuss/fix
@ales-t

**Comment by ozancaglayan** [comment]
@ales-t could we decide whether we want to change the way `asian_punctuation` behaves or do we want to keep it to preserve TERCOM compatibility?

**Comment by ales-t** [comment]
I would quite strongly prefer to maintain compatibility with TERCOM here. I agree that it has various quirks regarding both the preprocessing and the TER algorithm itself but as @ozancaglayan says, the point of sacrebleu is to provide a compatible reference implementation.

**Comment by ozancaglayan** [comment]
Ok then I think the README of the 2.0.0 would contain enough information for this. I'll try to make it even more clear.
