### ISSUE TITLE
Default value for "floor" BLEU smoothing

### ISSUE THREAD

**Issue by bricksdont** [mjpost/sacrebleu#129]
The default value for `floor` smoothing of counts for BLEU is `0.0`:

https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/metrics/bleu.py#L70

I think this means that if "floor" is used as the smoothing method and the value is not specified as an argument, then what happens here:

https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/metrics/bleu.py#L190

is that the precision for a particular ngram order is still `0.0` after smoothing.

Users of the compat API are currently getting those defaults for sentence BLEU:

https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/compat.py#L58

Wouldn't a small epsilon value (as in the original paper: http://aclweb.org/anthology/W14-3346) be a more reasonable default?

Thanks
Mathias

**Comment by ozancaglayan** [comment]
Hi @bricksdont 

This is part of an issue (#98) which remained unsolved. Since it has more content than this issue on the subject, I think it would be good if you add your comments there and we follow from there.

Thanks!
