### ISSUE TITLE
Travis-CI fails on Python3.5 because of portalocker

### ISSUE THREAD

**Issue by martinpopel** [mjpost/sacrebleu#137]
[A Travis-CI build](https://travis-ci.com/github/mjpost/sacrebleu/jobs/482898133) failed because the newest version of portalocker [uses type hints](https://stackoverflow.com/questions/66016216/getting-lock-file-syntax-error-when-importing-portalocker) via [variable annotations](https://www.python.org/dev/peps/pep-0526/) which is available only in Python 3.6+.

We can either drop Python 3.5 support or try to install older portalocker if Python==3.5.

**Comment by ozancaglayan** [comment]
Why do we need `portalocker` by the way @mjpost ? I checked TF and Torch's download utility functions and none of them implement locking.

**Comment by mjpost** [comment]
#31 is why we need portalocker. I'm open to alternatives, but I do think it's important we have it.

**Comment by ozancaglayan** [comment]
Ohh, quite edgy stuff : p
