### ISSUE TITLE
International tokenization

### ISSUE THREAD

**Issue by martinpopel** [mjpost/sacreBLEU#14]
First congrats: great idea, Rico! great implementation (and name), Matt.

The best practice when using mteval (by the way the newest version is [mteval-v14.pl](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl), the differences from v13a are not important, just the number is nicer) is to use [--international-tokenization](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl#L954-L982).
Of course, there won't be ever a consensus on the "ideal" tokenization (and Chinese, Japanese, Thai etc. will need a special approach anyway) and BLEU needs just "reasonable enough", but consistent tokenization. However, without the international-tokenization the correlation of BLEU with humans is much lower for languages with non-ascii punctuation, which includes also English with “typographic” quotes.

If you are interested I can send a PR with Python implementation of BLEU's international-tokenization.

**Comment by mjpost** [comment]
We could add a "intl" tokenization type triggered from the command line (`--tokenize intl`). I thought @alvations had made a similar suggestion somewhere though I can't seem to find it.

Note this repo is (currently mirrored in sockeye)[https://github.com/awslabs/sockeye/tree/master/contrib/sacrebleu] but that will soon become the primary place for ongoing bugfixes, so you may want to make your PR there instead.

**Comment by martinpopel** [comment]
OK, done in https://github.com/awslabs/sockeye/pull/218
Feel free to take the code and adapt as needed or throw away.

> I thought @alvations had made a similar suggestion somewhere

I guess you mean https://github.com/mjpost/sacreBLEU/issues/5 which is about better detection of Chinese characters, thus not really related to this.

**Comment by martinpopel** [comment]
Solved in https://github.com/awslabs/sockeye/pull/217 and https://github.com/awslabs/sockeye/pull/218.
I guess it will be mirrored to this repo soon, so closing this issue.

**Comment by mjpost** [comment]
Yes, and available now in pypi.
