### ISSUE TITLE
Scaling chrF and TER to 0-100

### ISSUE THREAD

**Issue by ozancaglayan** [mjpost/sacrebleu#140]
At least for chrF, the original implementation reports the score that way. Do you think it is reasonable to standardize these across the three metrics? It'll also make reportin a bit more consistent w.r.t to the `--width` parameter.

**Comment by martinpopel** [comment]
Yes, I would love that.
I think it is OK for everyone, especially if it will be in sacreBLEU 2.0, where such changes are expected.

**Comment by cfedermann** [comment]
+1
