### ISSUE TITLE
chrF not compatible with chrF++, Moses and NLTK for sentence-level smoothing

### ISSUE THREAD

**Issue by ozancaglayan** [mjpost/sacrebleu#144]
Created a new issue for this problem, to detach it from #121
See the comment: https://github.com/mjpost/sacrebleu/issues/121#issuecomment-786608571

To summarize, sacreBLEU applies effective order smoothing whereas others smooth with small value `eps`. The fix is already in my branch for sacreBLEU 2.0.0. The problem is to agree on whether we accept changing behavior for sentence-level chrF for >=2.0.0.

**Comment by martinpopel** [comment]
Yes, I vote for being compatible with the chrF++ implementation of chrF by default. We can keep the effective-order smoothing as a non-default option, or drop it (for chrF).
