### ISSUE TITLE
Make portalocker requirement more permitting?

### ISSUE THREAD

**Issue by shuoyangd** [mjpost/sacrebleu#146]
Hi,

I noticed that starting version 1.5.1, a new dependency portalocker==2.0.0 is added (previously there wasn't a version requirement). I realize portalocker is required because of #31, which doesn't look something that specifically calls for 2.0.0.

The issue is, there are packages that enforce dependency portalocker<=1.7.1 to enable back-compatibility with Python 2.7 (like [this one](https://github.com/Preston-Landers/concurrent-log-handler/issues/28)). While I realize that sacrebleu requires Python 3, a portalocker==2.0.0 dependency will create conflicts with other packages.

Can we make this more permitting?

Thanks,
Shuoyang

**Comment by ozancaglayan** [comment]
Hi,

This is only an issue for 1.5.1. The new portalockers do not support Python 3.5 and hence we pinned it to 2.0.0. The pinned dependency will not be there in the next sacreBLEU release.

**Comment by shuoyangd** [comment]
Oh good to know it’s temporary. Thanks!

Shuoyang

**Comment by ytsheng** [comment]
When will you guys have the next sacreBLEU release? I am running into the same issue. Trying to figure out whether to do a workaround or wait.
