### ISSUE TITLE
raise EOFError("No valid references for a sentence!") EOFError: No valid references for a sentence!

### ISSUE THREAD

**Issue by fenimi** [mjpost/sacrebleu#154]
I'm getting the EOFError: No valid references for a sentence when trying to evaluate an MT model in fairseq using sacrebleu. My evaluation files are correct and bilingual. I wonder what could be wrong. 

I'll appreciate any advice.

Thank you

**Comment by martinpopel** [comment]
How do you use `sacrebleu`? Can you provide a minimal example?

> My evaluation files are correct and bilingual

SacreBLEU does not need the source-language files. You provide just the system translation file and the reference translation (ideally, you specify the reference with `-t` and `-l` if it is one of the supported and automatically downloaded testsets).

**Comment by fenimi** [comment]
I'm using sacrebleu to evaluate after each epoch in fairseq. This is not the final testing phase. Here is an example of my validation set. 
```
Source: "ganduje responds to allegations of selling daula hotel - freedom radio nigeria ."
Target: "ganduje ya maida martani kan zargin saida otel ɗin daula - freedom radio nigeria ."
```
The source and target are stored in separate files. I use the key word "--eval-bleu" in fairseq.  I've used sacrebleu many times and I'm only reusing code I have always used and have never had this experience.

**Comment by martinpopel** [comment]
I guess the validation set consists of more than one sentence. The error
https://github.com/mjpost/sacrebleu/blob/5dfcaa3cee00039bcad7a12147b6d6976cb46f42/sacrebleu/metrics/bleu.py#L286
is triggered if there is a sentence with empty reference translation (empty string or `None`). So double check there are no empty lines in the reference file (including empty lines at the end of the file).
I am not familiar with Fairseq, so I cannot provide more help.

BTW: SacreBLEU should be used on non-tokenized (or de-tokenized) sentences, but your source and target seems to be tokenized (`nigeria .`). You can still use SacreBLEU, just the final scores won't be comparable to other works. Also, your sentences seem to be lowercased, but SacreBLEU is supposed to be applied on final translations to be provided to the users (i.e. after re-casing, if the raw output is lowercased) - there is an option `-lc` for case-insensitive BLEU, if needed. Both may be OK for your internal evaluation after each epoch. Just don't forget that the final evaluation on the post-processed translations may give different scores.

**Comment by fenimi** [comment]
Thank you so much, I found an empty line and that solved it. Thanks a lot.
