### ISSUE TITLE
BLEU class references

### ISSUE THREAD

**Issue by alexcoca** [mjpost/sacrebleu#156]
Hello,

For my application, I need to be able to change the NGRAM_ORDER of the BLEU object. I tried a few things, but because all the methods are static and access BLEU.NGRAM_ORDER which is always 4, I cannot see how to modify this attribute. Any suggestions?

**Comment by ozancaglayan** [comment]
Hi there,

In the upcoming version, the `BLEU` class will have a `max_ngram_order` argument passed into its `__init__` method. So programmatically, this will be possible at least.

**Comment by alexcoca** [comment]
Hello,

Thank you very much for letting me know. Any idea when this version will be released? I just ran out of ideas and I realised I have to copy paste the code and make the changes myself in the interim.

**Comment by ozancaglayan** [comment]
it's now in master, you can install the `master` version through `pip`, until the version is released.
