### ISSUE TITLE
Cannot import BLEU from sacrebleu.metrics

### ISSUE THREAD

**Issue by kanishkamisra** [mjpost/sacrebleu#159]
sacrebleu: 2.0.0
python version: 3.8

I am running the following code:

```python
from sacrebleu.metrics import BLEU

bleu = BLEU()
```
I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-834500773a9c> in <module>
----> 1 bleu = BLEU()

TypeError: __init__() missing 1 required positional argument: 'args'
```

EDIT: The compatibility API works, though.

**Comment by ozancaglayan** [comment]
Hi,

You probably are still using sacreBLEU 1.x but refer to the README.md file in the `master` repository. When 2.0.0 is finally released, the above method will work. Otherwise, the metric API in 1.x is experimental and not documented.

**Comment by Arij-Aladel** [comment]
ModuleNotFoundError: No module named 'sacrebleu.metrics'; 'sacrebleu' is not a package   the same problem the last version

**Comment by martinpopel** [comment]
This works for me with sacrebleu 2.0.0:
```python
from sacrebleu.metrics import BLEU 
bleu = BLEU()
```
Have you installed sacrebleu correctly? Can you confirm `python -c 'import sacrebleu; print(sacrebleu.__version__)'` prints `2.0.0`?

**Comment by mjpost** [comment]
One issue I’ve found is there can be multiple installations if you install as both root and your user account. Try `pip uninstall sacrebleu; sudo pip uninstall sacrebleu`, then resinstall.
