### ISSUE TITLE
Add sanity check for cached test sets

### ISSUE THREAD

**Issue by emjotde** [mjpost/sacreBLEU#16]
I interrupted sacreBLEU during the download of a WMT16 test set and did not realize it caches results, also incomplete results. Later usage kept using only 155 lines of the partially downloaded test set. Maybe sacreBLEU should check if the cached versions has the required number of lines?

**Comment by mjpost** [comment]
This is a good idea. I was thinking of adding an md5sum check or something of that nature.

**Comment by mjpost** [comment]
Version 1.1.7 now dies with an error if the input and reference streams have different lengths.
