### ISSUE TITLE
That's 100 lines that end in a tokenized period ('.') 

### ISSUE THREAD

**Issue by Arij-Aladel** [mjpost/sacrebleu#162]
what is the importance of these three warnings that I get them every time I calculate bleu score?

>             sacrelogger.warning("That's 100 lines that end in a tokenized period ('.')")
>             sacrelogger.warning("It looks like you forgot to detokenize your test data, which may hurt your score.")
>             sacrelogger.warning("If you insist your data is detokenized, or don't care, you can suppress this message with the `force` parameter.")

**Comment by martinpopel** [comment]
It is exactly as written in the warning (it is a single warning message on three lines). SacreBLEU expects detokenized input (both the hypothesis to be scored and the reference should be detokenized). SacreBLEU does tokenization internally, to make sure it is exactly the same tokenization for everyone (well, there are multiple tokenizations to choose from with `--tok`, but this choice is encoded in the SacreBLEU signature).

When a line ends with a space and period, there is a high probability the string was tokenized, i.e. it is not the final form which should be presented to users. When there are more than 100 such lines, the probability is much higher, so a warning is reported.

**Comment by Arij-Aladel** [comment]
Thanks for your reply! both hypothesis and the reference are already detokenized, hypothesis are generated by T5 model.

**Comment by Arij-Aladel** [comment]
@martinpopel Thanks for your reply! yes, it is clear I have them detokenized already to be as input to measure bleu score, and yes I have most of them ends with space then a period in both hypothesis and reference.  Ok another question please, is there any relation between bleu score and model loss?

**Comment by martinpopel** [comment]
Yes, there is a relation. BLEU usually correlates with the test loss (the higher BLEU, the lower loss) to some extent, esp. if computed on the same test set. This question is not related to the original issue (nor SacreBLEU), so I am closing it.
