### ISSUE TITLE
cannot import name 'main' from 'sacrebleu' 

### ISSUE THREAD

**Issue by i55code** [mjpost/sacrebleu#164]
Hi, 

After installing sacrebleu-2.0.0, the command line "sacrebleu" no longer works, even a simple command "sacrebleu --version" does not work. This is the error mesage.  

Traceback (most recent call last):
  File "/usr/local/bin/sacrebleu", line 6, in <module>
    from sacrebleu import main
ImportError: cannot import name 'main' from 'sacrebleu' (~/.local/lib/python3.8/site-packages/sacrebleu/__init__.py)

Really appreciate your help!

**Comment by ozancaglayan** [comment]
Closing as no feedback is provided. Feel free to re-open it if the issue still occurs.
