### ISSUE TITLE
Different result between Ocelot result and sacrebleu result.

### ISSUE THREAD

**Issue by BrightXiaoHan** [mjpost/sacrebleu#165]
I have created a submission on the wmt2021 en-zh news translation task. This is my best submission:
![image](https://user-images.githubusercontent.com/25839309/134449555-aa8ae6a8-1efb-42c2-860c-eab9bb9c2a55.png)

After the reference of test set released, I test my translation result by sacrebleu:
```
cat ~/tmp/wmt_submit/hyp-tgt/en-zh/pe/zh | sacrebleu ~/datasets/wmt2021test/en-zh.zh -l en-zh -m bleu -b -w 4
```
the result is 
![image](https://user-images.githubusercontent.com/25839309/134449721-bddf6356-23b3-411c-9f09-a95d93c2efd9.png)
Why did this happend.

**Comment by cfedermann** [comment]
Hi,

You did not specify the Chinese tokenizer (-tok zh), which OCELoT uses
(see:
https://github.com/AppraiseDev/OCELoT/blob/9237c1eb1d9feebb1a51966b8c1ef82b381b4b1e/leaderboard/models.py#L1046
).

Different tokenization choices will result in different scores.

Cheers and best, have a good day,
   Christian

**Comment by BrightXiaoHan** [comment]
Thanks for your reply. But I specify language pairs in my command:
```
-l en-zh
```
This will choose `zh` tokenizer in sacrebleu, which is the same as OCELoT.

**Comment by cfedermann** [comment]
Can you share the full signature of your SacreBLEU call?

**Comment by BrightXiaoHan** [comment]
```
cat ~/tmp/wmt_submit/hyp-tgt/en-zh/pe/zh | sacrebleu ~/datasets/wmt2021test/en-zh.zh -l en-zh -m bleu -b -w 4
```

**Comment by martinpopel** [comment]
@BrightXiaoHan To get the *SacreBLEU signature* exclude the `-b` in your call and post here the output.

**Comment by BrightXiaoHan** [comment]
<img width="1247" alt="截屏2021-09-23 下午10 26 34" src="https://user-images.githubusercontent.com/25839309/134525965-ee7f9f10-0c2a-4292-8169-a4de051e3950.png">

**Comment by BrightXiaoHan** [comment]
I have found the reason, sorry about that. There were some invalid lines when I extract raw text from xml files.
