### ISSUE TITLE
Add WMT21 datasets

### ISSUE THREAD

**Issue by DhruvAwasthi** [mjpost/sacrebleu#166]

**Comment by DhruvAwasthi** [comment]
Makes sense!
Thank you for the prompt reply!

**Comment by BrightXiaoHan** [comment]
When will version 2.1.0 be released?

**Comment by BrightXiaoHan** [comment]
Hi, I have a question here. In wmt21, some language directions, such as en-zh, have multipul reference. How can I reproduce the evaluation result 
 from http://wmt.ufal.cz/newstest2021-en-zh/.
```
sacrebleu refA -i hyp -l en-zh
``` 
or 
```
sacrebleu refA refB -i hyp -l en-zh
```

**Comment by martinpopel** [comment]
I see Human-B among the "systems" at http://wmt.ufal.cz/newstest2021-en-zh/,
and it has BLEU=27.94 (not 100), so I think it only ref-A (Human-A) was used as a reference
when computing BLEU scores at wmt.ufal.cz.
MT-ComparEval does not support multiple references and it does not use SacreBLEU internally,
although the scores should be (almost) the same as `sacrebleu -tok intl`.

Strangely, I don't see the question (https://github.com/mjpost/sacrebleu/issues/166#issuecomment-1141609834)
at GitHub, so I am replying via email.

Martin

----- Original Message -----
