### ISSUE TITLE
TER scores are not scaled

### ISSUE THREAD

**Issue by DhruvAwasthi** [mjpost/sacrebleu#169]
I am trying to calculate the TER score that should be in the range of 0-100. 
According to the new update, scores are scaled automatically.
The code that I am using to calculate scaled TER scores is:

```
metric = sacrebleu.metrics.TER()  
cal_score = metric.corpus_score(hypotheses, [references])
score = cal_score.score
```

But sometimes the score comes out to be greater than 100. 
Can you please tell me is it something that I am doing wrong or is it something else?

Thank you!

**Comment by ozancaglayan** [comment]
Hi,

As far as I know TER scores can be larger than 100 if the hypotheses are way too far from the references. This is also the case with the reference TERCOm library.

**Comment by DhruvAwasthi** [comment]
@ozancaglayan Even though TER scores can be larger than 100 then what is the meaning of "scaled TER scores"? 
Ideally, when we say scaled it should be within the scale.
