### ISSUE TITLE
Detokenize problem on wmt14'en-fr

### ISSUE THREAD

**Issue by hemingkx** [mjpost/sacrebleu#178]
Hi there,
     Thanks for your awesome work! When I use the scripts as follows:
```
bash scripts/sacrebleu.sh wmt14/full en fr ./test.out
```

I got only 35.6 score but when I use the detokenized official test set and the following command:
```
cat ./test.out.sorted.detok | sacrebleu ./test.fr.sorted.detok -m bleu -b -w 4
```

I got 42.5 score. I found this probably because the wmt14/full en-fr.fr is not detokenized well, like line 4:
```
Une boîte noire dans votre voiture ?
```

It should be:
```
Une boîte noire dans votre voiture?
```

Maybe there is something that I misunderstand, I appreciate it very much if you can check this issue.

Thanks,
hemingkx

**Comment by ozancaglayan** [comment]
Hi,

I don't get what is inside `scripts/sacrebleu.sh` so it's difficult to tell whether this is related to a bug in sacrebleu/test sets or something else. Could you elaborate further? A difference of that much in BLEU should not be related to minor tokenization issues.

**Comment by martinpopel** [comment]
> en-fr.fr is not detokenized well, like line 4:
> Une boîte noire dans votre voiture ?

Note that unlike English, French (as written in France) [requires](https://en.wikipedia.org/wiki/French_orthography#Punctuation) a narrow non-breaking space before the question mark and several other punctuation symbols. It is quite often normalized into a standard space. So the quoted sentence is correct.

That said, sacreBLEU uses a tokenization internally, which separates the question mark anyway, so the presence/absence of a space before question marks in reference/hypothesis does not affect the final score.
However, [guillemet](https://en.wikipedia.org/wiki/Guillemet) symbols are separated only with `-tok intl`, not with the default "13a" tokenization, so you should make sure that your hypothesis uses space inside these quotation marks in the same way as the reference (with space for France-, without for Canada- origin texts), or use `-tok intl`.

**Comment by hemingkx** [comment]
> That said, sacreBLEU uses a tokenization internally, which separates the question mark anyway, so the presence/absence of a space before question marks in reference/hypothesis does not affect the final score. However, [guillemet](https://en.wikipedia.org/wiki/Guillemet) symbols are separated only with `-tok intl`, not with the default "13a" tokenization, so you should make sure that your hypothesis uses space inside these quotation marks in the same way as the reference (with space for France-, without for Canada- origin texts), or use `-tok intl`.

 Thanks very much! I added `-tok intl` and solved the problem.
