### ISSUE TITLE
Is ‘extract_ngrams’ removed in the latest version?

### ISSUE THREAD

**Issue by rangehow** [mjpost/sacrebleu#188]
When I try to run example code in fairseq , the following error occured:

> Traceback (most recent call last):
    from sacrebleu import extract_ngrams
ImportError: cannot import name 'extract_ngrams' from 'sacrebleu' (D:\miniconda\lib\site-packages\sacrebleu\__init__.py)

So if this is a deprecated function in lateset sacrebleu, what is the optional function to call in 2.0.0 or which version  maintains 'extract_ngrams'?

Looking forward to your reply sincerely.

**Comment by martinpopel** [comment]
You can
* downgrade sacrebleu to 1.5 or
* continue using sacrebleu >= 2.0 and use `from sacrebleu.metrics.helpers import  extract_all_word_ngrams as extract_ngrams` or
* if this is the only code needed from sacrebleu, you can copy [the 7 lines of code](https://github.com/mjpost/sacrebleu/blob/v1.5.1/sacrebleu/metrics/bleu.py#L105-L122)

**Comment by rangehow** [comment]
Appreciate it, thanks for your help! : )
