### ISSUE TITLE
Scores per item

### ISSUE THREAD

**Issue by evanmiltenburg** [mjpost/sacrebleu#19]
It would be useful to have the individual scores for each hypothesis. 

I know that the sentence_bleu function says that "computing BLEU on the sentence level is not its intended use, BLEU is a corpus-level metric", but it might be useful to check for outliers.

**Comment by mjpost** [comment]
You could do this via the API:

```
import sacrebleu
for line in sys.stdin:
    out, ref = line.rstrip().split('\t')
    print(sacrebleu.sentence_bleu(out, ref))
```

Or did you have something else in mind?
