### ISSUE TITLE
How to calculate the chrf2 score?

### ISSUE THREAD

**Issue by RamoramaInteractive** [mjpost/sacrebleu#193]
I've an output and a reference:

Reference: Das ist das Haus von Tom and Sam
Output: Das ist das Haus von Thomas und Samuel

When I use Sacrebleu I got a score of **0.75**.

I got as Recall **0.65** ans as Precision **0.5**. I used 6-gram as character order and after calculating with the formular on paper I got 0.6132.

Why is my different? My Beta is 2.

**Comment by ozancaglayan** [comment]
could you maybe check with the original implementation to see if this is a difference that arise in sacreBLEU's chrF implementation?

https://github.com/m-popovic/chrF

**Comment by ozancaglayan** [comment]
closing as no answers.
