### ISSUE TITLE
Why give 0 bleu score when evaluating De ?

### ISSUE THREAD

**Issue by Hannibal046** [mjpost/sacrebleu#198]
Hi, do I understand this correctly ? Could anyone help me out ?
```
def get_bleu_score(hyps,refs,return_signature=False):
    # pip install sacrebleu
    """
    hyps:list of string
    refs:list of string
    """
    assert len(hyps) == len(refs)
    
    import sacrebleu
    scorer = sacrebleu.BLEU(force=True)
    score = scorer.corpus_score(hyps,[refs]).score
    signature = scorer.get_signature()
    if return_signature:
        return score,str(signature)
    else:
        return score
```
This is the result of `DE`
```
hyp = "Generaldirektion Informationsgesellschaft"
ref = "Generaldirektion Informationsgesellschaft"
get_bleu_score([hyp],[ref]) --> 0.0
```

This is the results of `EN`
```
hyp = "The dog bit the man."
ref = "The dog had bit the man."
get_bleu_score([hyp],[ref]) --> 51.15
```

**Comment by martinpopel** [comment]
BLEU is based on a geometric mean of unigrams up to 4-grams. If there is no matching 4-gram in the whole testset, BLEU is 0 by definition (unless some kind of sentence-BLEU smoothing is used). In general, BLEU is reliable only for testsets with at least hundreds of sentences.

**Comment by Hannibal046** [comment]
Got it. Thanks so much. BTW, if I don't specify the target language, how does sacrebleu identify it ?

**Comment by martinpopel** [comment]
BLEU definition is the same for all languages. SacreBLEU command-line interface uses `-l en-de` just* for selecting (and downloading if not downloaded) the correct testset (specified with `-t`), but when using the API `corpus_score` method (or when [using your own reference in CLI](https://github.com/mjpost/sacrebleu#using-your-own-reference-file)), there is no need to specify the target (nor source) language.

*) When the target language is specified as Chinese or Japanese, it [influences also the default tokenizer](https://github.com/mjpost/sacrebleu/blob/65a8a9eeccd8c0c7875e875e12edf10db33ab0ba/sacrebleu/metrics/bleu.py#L141-L146).
