### ISSUE TITLE
Installing latest version via PIP results in an error

### ISSUE THREAD

**Issue by epwalsh** [mjpost/sacrebleu#209]
Hey, I got this error:

![image](https://user-images.githubusercontent.com/8812459/189974542-37f3a4be-3554-44cb-ac83-e3dc799b31ec.png)

Looks like the CHANGELOG is not bundled with the distribution?

**Comment by ztanruan** [comment]
same error ? How do we fix this ?

**Comment by Hadrien-Cornier** [comment]
I have the same issue as well

**Comment by cabal-daniel** [comment]
same here

**Comment by rouven-idalab** [comment]
Same

**Comment by SimengSun** [comment]
Same issue here

**Comment by RouvenG** [comment]
Same

**Comment by yangky11** [comment]
Same issue. It is because the file CHANGELOG.md is missing in the tar file on PyPI

**Comment by mjpost** [comment]
Hi everyone,

Sorry, I never saw this—but this was fixed in 2.2.1. I know what caused the error and it shouldn't happen again.
