### ISSUE TITLE
automatically pick tokenizer when known

### ISSUE THREAD

**Issue by frankseide** [mjpost/sacreBLEU#22]
Hi, when adding the `en-zh` direction to my work setup, I got this message:
```
sacreBLEU: You should also pass "--tok zh" when scoring Chinese...
```
This is causing problems because it makes the command line irregular, in that for some languages, a different command-line pattern is needed. This makes it unnecessarily complex to wrap it in scripts that accept e.g. the language pair as an argument. Such scripts are often just one-line pipelines that detokenize and then pipe the result to Sacrebleu, passing some of their arguments directly down to the tools they invoke without further processing.

Could Sacrebleu please automatically choose the correct default tokenizer based on the language, whenever it has enough information to do so?

Thanks!

**Comment by mjpost** [comment]
Done, and [pushed to pypi](https://pypi.org/project/sacrebleu/). Should be available via `pip` shortly.

**Comment by frankseide** [comment]
Nice, thanks!!
