### ISSUE TITLE
Calculate sentence-level and corpus-level BLEU with tokenizer flores101(or flores200) on GPU

### ISSUE THREAD

**Issue by ElizabethUniverse** [mjpost/sacrebleu#227]
Hello, I'm Liza
Is it possible to calculate sentence-level BLEU scores with tokenizer flores101 on GPU? 
I think it would be great, because it will saves a lot of time. Currently sentence_bleu calculates 1000 scores in 1 minute, and it would be greate to speed up this.
Thank you a lot!

**Comment by BramVanroy** [comment]
I'd suggest to instead parallellize your code over multiple cores. GPU does not make much sense here.

**Comment by ozancaglayan** [comment]
Hello,

Unfortunately GPU would not be very helpful in this case and there are no plans to add GPU support to sacreBLEU.

Thanks!
