### ISSUE TITLE
Schedule a new release

### ISSUE THREAD

**Issue by daskol** [mjpost/sacrebleu#241]
@mjpost Are you planning to release a new version? It is a little bit confusing. It seems that release tag [v2.3.1][1] is out of main branch (missing commit c7fc1663ec8b0840edaadb59e21523c82d9e9c31) while several changes have been made to trunk for the last year.

[1]: https://github.com/mjpost/sacrebleu/commits/v2.3.1

**Comment by mjpost** [comment]
Thanks, this had escaped my attention. I'll do a new release with the WMT23 data as well.

**Comment by mjpost** [comment]
Okay, I just added release 2.3.2. Thanks for calling this to my attention. WMT23 data will get added in a 2.4.0 release.
