### ISSUE TITLE
Taking a long time to download the test set

### ISSUE THREAD

**Issue by Phuoc-Hoan-Le** [mjpost/sacrebleu#242]
Running the command `sacrebleu -t wmt17 -l en-de --echo src > wmt17.en-de.en`, now takes forever. Before  I could run this command in less than a minute. How come now it is taking me forever?

**Comment by martinpopel** [comment]
This is because `wget http://data.statmt.org/wmt17/translation-task/test.tgz` takes forever. It seems the whole `data.statmt.org` server is now affected. If it takes longer, maybe @bhaddow could help.

**Comment by Phuoc-Hoan-Le** [comment]
@martinpopel when will this issue be resolved? Thanks!

**Comment by bhaddow** [comment]
I'm in the process of setting up a new server, but it will be a few weeks more before it is ready. The current one gets overloaded very easily.
