### ISSUE TITLE
Removing the change of behavior regarding SIGPIPE from the top-level

### ISSUE THREAD

**Issue by jblespiau** [mjpost/sacrebleu#268]
Hi,

this is about the code at https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/sacrebleu.py#L51-L60 which is changing the say SIGPIPE is handled by any binary transitively importing `sacrebleu`.

1) I have understood it's here to fix "broken pipe" errors when using sacrebley as a command line:
- https://github.com/mozilla/sacreBLEU/commit/13966eadb4d7133330b1a40a02476ac7fe74c311 (I know it's a different repo, but I expect the history to be the same).
- https://stackoverflow.com/a/30091579/891821

2) I don't think the full library should be changing the way SIGPIPE is handled. It's explicitly siad in the Python documentation to not do that. See https://docs.python.org/3/library/signal.html#note-on-sigpipe

What about: e.g.

- moving the code block to `main`,
- or remove the code block in favor of the method described in https://docs.python.org/3/library/signal.html#note-on-sigpipe, for the `main() function?

Thanks.

**Comment by martinpopel** [comment]
Thanks for the suggestion. Can you send a PR?
The `signal(SIGPIPE,SIG_DFL)` line [was added](https://github.com/mjpost/sacreBLEU/commit/13966eadb4d7133330b1a40a02476ac7fe74c311) in 2017 when `sacrebleu.py` was a single-file command-line utility (even then it could be used as a library, but perhaps it was not the primary use case). I agree that now when the library use case is officially supported, we should move the code block below the `if __name__ == '__main__'` condition and/or catch specifically the `BrokenPipeError` exception as suggested in the Python documentation. We don't support Python 2 anymore.
