### ISSUE TITLE
(minor) factor tokenizer code

### ISSUE THREAD

**Issue by frankseide** [mjpost/sacrebleu#27]
Hi, there are three tokenizers, and at least two of them (`tokenize_13a()` and `tokenize_zh()`) contain the same processing steps for tokenizing Western-script characters. The code is not even identically written, although the regexes seem identical in the end. Code duplication is dangerous, in case future modifications are ever made to this code. I suggest to factor out this code.

**Comment by mjpost** [comment]
It’s a good idea. The main reason I haven’t is because it requires some other work setting up regressions tests and so on to make sure I don’t break anything, but I’ll queue it up. Outside contributions are always welcome, of course :)
