### ISSUE TITLE
sacreBLEU computation for multiple target translations?

### ISSUE THREAD

**Issue by ashutoshsaboo** [mjpost/sacreBLEU#28]
Hi, is it possible to compute sacreBLEU for multiple reference/target translations for a particular hypothesis translation in the corpus? Normal BLEU can be computed in such a scenario, by just providing a list of references for each hypothesis - however I tried the same with sacreBLEU, and it breaks. 

Any inputs on the same, would be really helpful! Thanks!

**Comment by mjpost** [comment]
It should work to give multiple references. Can you provide an example where it failed, and what the error message was?

**Comment by ashutoshsaboo** [comment]
I called the method `sacrebleu.corpus_bleu(target, [predictions])` 
where target[i] was a list of references for each predictions[i]. but the error message is `  File "sacrebleu.py", line 1224, in corpus_bleu
  sacrebleu.py", line 1224, in <listcomp>
AttributeError: 'list' object has no attribute 'rstrip'` . Is there a different format to provide multiple references?

**Comment by mjpost** [comment]
That [is not the signature](https://github.com/mjpost/sacreBLEU/blob/dce5a55523b45f9b2b8cc50b950ed1adee978ffc/sacrebleu.py#L1199) for `corpus_blue`:

```
def corpus_bleu(sys_stream:
                ref_streams,
                smooth_method='exp',
                smooth_value=SMOOTH_VALUE_DEFAULT,
                force=False,
                lowercase=False,
                tokenize=DEFAULT_TOKENIZER,
                use_effective_order=False) -> BLEU:
```

The first argument is the system output as a stream (so, an open file handle, or a list of strings, if you've read them all in). The second argument is a *list of lists* of references (e.g., a list of open file handles, or a list of lists of strings, one top-level list for each reference).

**Comment by ashutoshsaboo** [comment]
Thanks, yes I was essentially doing the same thing, just had reversed the target, and predictions in the signature. 
So now I'm basically calling `sacrebleu.corpus_bleu(predictions, targets)` , where predictions is a list of strings, and targets is a list of list of references - for each predictions[i], targets[i] is the list of references (variable for each predictions[i]). 

However, it complains with the following error:
`EOFError: Source and reference streams have different lengths!` . I re-checked, and len(predictions)=len(targets). Is this because - variable number of targets for each prediction? Could you help please? Thanks!

**Comment by mjpost** [comment]
`len(predictions)` should not equal `len(targets)`, because `targets` is a list of parallel streams, each of which should be the same length as `predictions`.

**Comment by ashutoshsaboo** [comment]
Thanks @mjpost ! Sorry but something weird seems to happen. `sacrebleu.corpus_bleu(predictions, targets)` works perfectly if targets is a list of list of references - where `len(predictions)=len(targets)` and `len(targets[i]) is equal for each i`, however fails for the variable length of targets for each prediction. Am I doing something wrong here, or is this expected? 

Say, if predictions = ['a','b','c'] and targets=[['d','e'],['f','g','h'],['i']] where targets[i] is the list of targets for each of predictions[i], then how would you pass it to `corpus_bleu`?

**Comment by ashutoshsaboo** [comment]
Thanks @mjpost ! Sorry but what you mentioned works in the case if there's a single reference for each prediction, and not for the multiple references case. 

Say, if predictions = ['a','b','c'] and targets=[['d','e'],['f','g','h'],['i']] (using characters here in place of sentences for simplicity) where targets[i] is the list of targets for each of predictions[i], then how would you pass it to `corpus_bleu`? If you could please help with this toy example, then it'd be really helpful! :)

**Comment by ashutoshsaboo** [comment]
Alright, everything works fine as you suggested! Thanks @mjpost !

**Comment by MT010104** [comment]
> Alright, everything works fine as you suggested! Thanks @mjpost !

Hi, I met the problem with you. So can I conclude that NLTK's implementation of BLEU does support variable number of multiple references and sacreBLEU doesn't support it?
