### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by mjpost** [mjpost/sacreBLEU#3]
It would be nice to support Python 2, I guess. This would require at least unicode handlers for file streams, likely different downloading code, and maybe some other small things.

**Comment by alvations** [comment]
I think it's not worth the effort. 

But lets just do that just in case we never get to see [2020](https://pythonclock.org)

**Comment by ozancaglayan** [comment]
Thanks for this project but in order to move people from Py2 to Py3, I think its better to not spend the effort at all.
