### ISSUE TITLE
Running two or more instances of sacrebleu in a pipe does not lock temp files

### ISSUE THREAD

**Issue by emjotde** [mjpost/sacreBLEU#31]
Hi,
When I run a command where sacrebleu is used multiple times like this (I do this all the time):

`./sacrebleu.py -t wmt16 -l ende --echo src | ./generic_translator | ./sacrebleu.py -t wmt16 -l ende`

the two instances may overwrite each others temporary files when the test set is being downloaded for the first time. Both instances then start downloading, unpacking, etc. They may end-up corrupting the files.

**Comment by mjpost** [comment]
I just added this in commit f3c32bb (branch `lockfile`)—do you have time to test it before I release it?

**Comment by emjotde** [comment]
Seems to work. The added dependency on `portalocker` is a bit unfortunate.

**Comment by mjpost** [comment]
Hmm. I suppose I could do this with a bare non-atomic file lock. The race condition isn't really that much of a worry.
