### ISSUE TITLE
The Choice of Detokenization Methods

### ISSUE THREAD

**Issue by jcyk** [mjpost/sacrebleu#39]
Hi, 
Just a couple of questions since we need to detokenize data before evaluation.
Will the choice of detokenization method affect the BLEU score?
Which detokenization method is the best choice?

**Comment by mjpost** [comment]
Yes, the detokenization and normalization will have some effect. The general answer is that you should detokenize so as to be closest to the form the reference takes. One issue that doesn’t come out in papers often is that of normalization. For example, if the references uses smart quotes, but your output uses straight quotes, it can have a large effect on the BLEU score, if your corpus has a lot of quotations.

**Comment by martinpopel** [comment]
A related question for @mjpost: Would you welcome a PR with `--no-punct` option, which deletes all punctuation (from both the reference and translation)? As for the signature, it could either add "no-punct" to the tokenization method, or introduce "+punct.no" (but I don't want to make the default signature any longer). This option could be helpful when detecting e.g the effect of smart/straight quotes. It is similar to lowercasing in its nature.

**Comment by mjpost** [comment]
Yes, this sounds great. There’s a great universal implementation from @arya.mccarthy we could borrow from here:

    https://github.com/duolingo/duolingo-sharedtask-2020/blob/a000131a8714a6832069cfc0b281a187e8ed3eb6/utils.py#L51

(agree about keeping default sig shorter. Wish I’d put more thought into it (e.g., invertible Geek codes)

matt (from my phone)
