### ISSUE TITLE
Feature Request: Port the significance test?

### ISSUE THREAD

**Issue by felix-schneider** [mjpost/sacrebleu#40]
In moses, there is [this script](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/analysis/bootstrap-hypothesis-difference-significance.pl) for determining the "true" BLEU score within a confidence interval. Unfortunately, it does not have the configurability that sacreBLEU has.

In order to compare systems with regard to statistical significance, it would be nice to have a similar script, but supporting sacreBLEU.

**Comment by martinpopel** [comment]
See #11

**Comment by mjpost** [comment]
Yes, I'd love to have this in sacrebleu. It's just looking for a contributor...

**Comment by martinpopel** [comment]
The *paired* property is the main obstacle when adding paired bootstrap to SacreBLEU - we would need to change the interface, so that you can provide multiple systems' translations at once. SacreBLEU currently expects the system translation on the stdin and does not provide a way to name the system. We would need to change this e.g. to accepting tab-separated systems on the input and optionally providing system names, e.g. `paste moses.txt nematus.txt | sacrebleu --bootstrap_samples=10000 --system_names=Moses,Nematus reference.txt`.

**Comment by ozancaglayan** [comment]
maybe the significance part can be a wrapper command around sacrebleu?

**Comment by martinpopel** [comment]
Efficient implementation of bootstrap does not call `sacrebleu` 10000 times (doing the tokenization 10000 times), so a "wrapper command around sacrebleu" is not a proper solution. We could provide `sacrebleu-bootstrap` command, which would take multiple systems' translations on the input (and optionally their names as `--system-names`) and the number of resamples as a parameter, but I don't see any advantage over keeping this within `sacrebleu`.

**Comment by cfedermann** [comment]
I had implemented this way back but the feature was lost in a refactoring.
Can look into bringing it back into the current code base.

@mjpost, feel free to assign to me.

**Comment by martinpopel** [comment]
Hi @cfedermann, I linked your implementation (#11) above (so it is not completely lost), but it doesn't do *paired* bootstrap resampling, so I also linked [a Python implementation of paired bootstrap](https://github.com/Gldkslfmsd/MTCE-py/blob/master/mtce/bootstrap.py) (by a student of mine), which is actually built on top of `sacrebleu`.

**Comment by ozancaglayan** [comment]
Hi,

I want to spend some time on sacrebleu during the following days and
apparently there are enough materials around for integrating so I can try
to look at this as well.

There's also a recent PR about this, which you may want to review.

An additional question is: I saw somewhere in a slidedeck that (paired)
approximate randomization is a better method for MT than (paired) bootstrap
resampling. What is your take on this?

**Comment by cfedermann** [comment]
I'd implement and offer both bootstrap and AR, that makes everybody happy...

**Comment by ozancaglayan** [comment]
The implementation of this feature requires the ability to provide `N` input files when running sacreBLEU. If we were to only use `-i`, this should have been easier but we also support reading from `STDIN`. I can't easily see a solution without breaking backward compatibility: we can read `\t` separated stream from `STDIN` and when `--input -` is given, but we can't use the same `--input` for `nargs`-style multiple arguments at the same time.

What are your thoughts on this? Maybe we can keep the API as the same but add `--system-files` and `--system-names` for significance test but I'm scared that this will pollute/confuse the codebase a lot.

**Comment by mjpost** [comment]
Why can't we use both at the same time? Couldn't we write an input wrapper that (a) receives `args.input` and returns a set of input streams? In the case that `args.input == sys.stdin`, it would split on tabs and return a stream.

We could also support this feature only with `-i`, if that were easier.

**Comment by ozancaglayan** [comment]
I think the main problem is related to argparse here, rather than STDIN-reading as I previously told.

`--input` was defined to be a `str` with a default of `-`. `refs` are defined to be a positional argument without a hyphen prefix and it expects to read 0 or more references i.e. `nargs='*'`.

I don't think we can have two arguments with `nargs='*'`. This eliminates the easiest form of use i.e. `--input rnn/hypotheses transformers/hypotheses smt/hypotheses`. This leaves us with the only option of preparing everything as a tab separated file and giving it to `--input`, which is pretty cumbersome.

If I were to break compatibility, I would suggest to not have `refs` as positional arguments and instead use `--refs`.

```
sacrebleu -i rnn/hyps transformers/hyps smt/hyps -r refs
sacrebleu -i rnn/hyps -r refs
sacrebleu -i - -r refs (with - being tsv file or single file)
```

Please correct me if I'm missing something.

**Comment by martinpopel** [comment]
First, I think `sacrebleu ref1 ref2 ref3 --input in1 in2` should work.
Second, `paste in1 in2 | sacrebleu ref1 ref2 ref3` should not be cumbersome.
So I think we could continue supporting both `--input` and stdin, even with more input files.
Just in the case of tab-separated stdin, we perhaps should requite an option indicating how many input systems to expect, so that we can report errors with unexpected number of columns (similarly as we do with tab-separated references and `-nr 2`).

**Comment by ozancaglayan** [comment]
```
sacrebleu ref1 ref2 ref3 --input in1 in2 --> works
sacrebleu --input in1 in2 ref1 ref2 ref3 --> obviously, no go :) Do we care about this slight ambiguity?
```

For the paste case, and the number of systems; I think `--names` would solve that as well directly? So all of these below should work equivalently if we are on the same page then.

```
sacrebleu ref1 ref2 ref3 \
  --names 2_layer_rnn pbsmt \
  --input rnn/hyps moses/hyps

paste rnn/hyps moses/hyps | sacrebleu ref1 ref2 ref3 \
  --names 2_layer_rnn pbsmt \
  --input -

paste rnn/hyps moses/hyps | sacrebleu ref1 ref2 ref3 \
  --names 2_layer_rnn pbsmt
```

**Comment by ozancaglayan** [comment]
I progressed a bit. The above commands work now, except that I did not add `--names`. System names become the basenames of given file names. For STDIN, they are simply `sys1, sys2, ..., sysN`. The number of systems in the STDIN stream is automatically assumed to be the number of fields in the **first** line, so I did not add the equivalent of `-nr` either.

It kind of works now for I/O processing and reporting. Even without significance testing, this also has the ability to provide a table of results through the `tabulate` PyPI package. If you are OK to add it as a dependency, it also allows a plethora of output formats including plain text, latex, github markdown, etc. I think significance testing results may also be reported this way, for multiple metrics as in the `multeval` toolkit.

```
paste wmt17-submitted-data/txt/system-outputs/newstest2017/cs-en/newstest2017.PJATK.4760.cs-en \
 wmt17-submitted-data/txt/system-outputs/newstest2017/cs-en/newstest2017.uedin-nmt.4955.cs-en | \
   ../sacrebleu/sacrebleu.py -l cs-en ref1 ref2 -m bleu chrf

\begin{tabular}{lrr}
\toprule
 System   &    BLEU &    chrF2 \\
\midrule
 sys1     & 44.6732 & 0.649777 \\
 sys2     & 60.8451 & 0.702234 \\
\bottomrule
\end{tabular}
```

```
sacrebleu -l cs-en ref1 ref2 \
  -i wmt17-submitted-data/txt/system-outputs/newstest2017/cs-en/newstest2017.PJATK.4760.cs-en \
     wmt17-submitted-data/txt/system-outputs/newstest2017/cs-en/newstest2017.uedin-nmt.4955.cs-en \
     -m bleu chrf

\begin{tabular}{lrr}
\toprule
 System                            &    BLEU &    chrF2 \\
\midrule
 newstest2017.PJATK.4760.cs-en     & 44.6732 & 0.649777 \\
 newstest2017.uedin-nmt.4955.cs-en & 60.8451 & 0.702234 \\
\bottomrule
\end{tabular}
```

**Comment by ozancaglayan** [comment]
Looking back at the initial implementation of @cfedermann , I saw that it was computing simply CIs, and not comparing two systems against each other+providing p-values. What is the type of functionality we desire here?

**Comment by ozancaglayan** [comment]
Working on this these days,

The caching of tokenized outputs and match statistics is done. The question is: Do we want just bootstrap CIs or paired testing that'll allow ingesting multiple systems and probably computing p-values?

**Comment by martinpopel** [comment]
Thanks for the work. The LaTeX output looks great.
I think paired bootstrap is the feature most users want from BLEU bootstrap (although sometimes they don't know they want it). Computing non-paired CIs for each system and then checking if they overlap is the wrong way for checking if one system is significantly better than another system (the CI are wide because some sentences are easier/more difficult to translate, but perhaps in a similar way for all the systems).

**Comment by ozancaglayan** [comment]
Reasonable. So it would be more like the `multeval` toolkit's way of doing things rather than the Perl script in moses.

**Comment by ozancaglayan** [comment]
What do we think on adding `numpy` as a dependency? `np.random.choice` seems to be the fastest solution for sampling with replacement: Negligible slowdown with `n_bootstrap` < 1000, ~3x slowdown with `n_bootstrap=10000`.

**Comment by martinpopel** [comment]
I have `numpy` installed on all the system I use, so I don't see a problem with adding it as a dependency. I am not sure about other users of sacrebleu.

If you use `numpy` only for the resampling, you could also add it as recommended only and `try: import numpy; ...` and if it is not available, use the slower way. However, this would complicate testing and using `numpy` in other parts of sacrebleu.

**Comment by ozancaglayan** [comment]
We now support multiple system result production in my WIP branch. This is a pre-requisite for paired significance tests. As discussed previously in another issue (too many issues same topics, can't get hold; I'll stick with here from now on),

1) `--input` now supports ingesting a variable number of text files. Its default is `None` which preserves the `STDIN` behaviour as usual. We presume the `basenames` determine a given system's name for the sake of clarity. If the same basename re-occurs, we give an error with a readable message.

```
$ sacrebleu -w 4 -i newstest2017/cs-en/*en -t wmt17 -l cs-en -m bleu chrf
Evaluating 'newstest2017.online-A.0.cs-en'
Evaluating 'newstest2017.online-B.0.cs-en'
Evaluating 'newstest2017.PJATK.4760.cs-en'
Evaluating 'newstest2017.uedin-nmt.4955.cs-en'
+-----------------------------------+--------+---------+
| System                            |   BLEU |   chrF2 |
+===================================+========+=========+
| newstest2017.online-A.0.cs-en     |  25.12 |    0.53 |
+-----------------------------------+--------+---------+
| newstest2017.online-B.0.cs-en     |  27.45 |    0.54 |
+-----------------------------------+--------+---------+
| newstest2017.PJATK.4760.cs-en     |  23.15 |    0.53 |
+-----------------------------------+--------+---------+
| newstest2017.uedin-nmt.4955.cs-en |  30.95 |    0.57 |
+-----------------------------------+--------+---------+```
```

2) If `STDIN` given, tab-separated hypotheses will be parsed where `len(fields)` determined the number of systems to evaluate. No system names can be given in this case.

```
$ paste newstest2017/cs-en/*en | sacrebleu/sacrebleu.py -w 4 -t wmt17 -l cs-en -m bleu chrf
Evaluating 'sys1'
Evaluating 'sys2'
Evaluating 'sys3'
Evaluating 'sys4'
+----------+--------+---------+
| System   |   BLEU |   chrF2 |
+==========+========+=========+
| sys1     |  25.12 |    0.53 |
+----------+--------+---------+
| sys2     |  27.45 |    0.54 |
+----------+--------+---------+
| sys3     |  23.15 |    0.53 |
+----------+--------+---------+
| sys4     |  30.95 |    0.57 |
+----------+--------+---------+

```

3) A behavioral change: `refs` should now preceed `--input` otherwise `argparse` can't differentiate between `refs` and `inputs`. Not a problem when pre-shipped test set refs are used with `-t`.

4) Significance mode will be then enabled as follows:

```
$ paste newstest2017/cs-en/*en | sacrebleu/sacrebleu.py -w 4 -t wmt17 -l cs-en -m bleu chrf --sig-test --n-bootstrap 1000

OR

$ sacrebleu -w 4 -i newstest2017/cs-en/*en -t wmt17 -l cs-en -m bleu chrf --sig-test --n-bootstrap 1000

```

5) Since the tokenization of hypotheses and references are done in a very lazy way, when computing the actual BLEU statistics, I added an `lru_cache` to the BLEU tokenizers. This allows returning an already tokenized sentence if there's a cache hit, avoiding redundant reference tokenizations in multi-system mode. For 11 en-de systems, the script performs evaluation in ~11.7s` without cache and `9.7s` with the cache.

**Comment by ozancaglayan** [comment]
I have a working prototype for bootstrap resampling across all metrics. Didn't proceed for paired tests but weirdly all I get is a %95 CI of ~0.02 (n_bootstrap=1000):

I'll investigate further but the good part is that the interface now supports everything that we need for doing multi-system multi-metric evaluation.

```
+-----------------------------------+---------------------+---------------------+---------------------+
| System                            | BLEU                | chrF2               | TER                 |
+===================================+=====================+=====================+=====================+
| newstest2017.online-A.0.cs-en     | 25.1118 (+/- 0.019) | 53.3858 (+/- 0.016) | 63.6480 (+/- 0.024) |
+-----------------------------------+---------------------+---------------------+---------------------+
| newstest2017.online-B.0.cs-en     | 27.4547 (+/- 0.021) | 54.4541 (+/- 0.016) | 60.4857 (+/- 0.023) |
+-----------------------------------+---------------------+---------------------+---------------------+
| newstest2017.PJATK.4760.cs-en     | 23.1360 (+/- 0.020) | 52.6040 (+/- 0.017) | 66.4286 (+/- 0.025) |
+-----------------------------------+---------------------+---------------------+---------------------+
| newstest2017.uedin-nmt.4955.cs-en | 30.9549 (+/- 0.022) | 56.8429 (+/- 0.017) | 58.4359 (+/- 0.025) |
+-----------------------------------+---------------------+---------------------+---------------------+

Metric signatures:
 bleu       bstrap.1000+case.mixed+numrefs.1+seed.12345+smooth.exp+tok.13a+version.2.0.0
 chrf       bstrap.1000+case.mixed+nchars.6+nwords.0+seed.12345+space.false+version.2.0.0
 ter        asian.False+bstrap.1000+case.lc+norm.False+numrefs.1+punct.True+seed.12345+tok.tercom+version.2.0.0
```
