### ISSUE TITLE
About Translationese

### ISSUE THREAD

**Issue by andyweizhao** [mjpost/sacrebleu#49]
Does scoring translationese get ready to release? I did not find a piece of code about this feature in sacrebleu.py except "--origlang=de". By the way, can you kindly provide the reference upon which you are implementing for scoring translationese?

**Comment by martinpopel** [comment]
My PR (#43) regarding translationese was already merged and released on PyPI (together with [other improvements](https://github.com/mjpost/sacreBLEU/blob/master/CHANGELOG.md)) in sacrebleu 1.4.0.
The code implementing `--origlang` is [here](https://github.com/mjpost/sacreBLEU/pull/43/files). It works with any language code, not only with `de` (of course, only if the annotation is available in the respective sgm files).
There are several recent papers related to the topic (e.g. [this](https://arxiv.org/abs/1906.09833) or [this](https://arxiv.org/abs/1908.05204)).

**Comment by andyweizhao** [comment]
Thank you very much for the swift reply! I can run properly with "--origlang", but I am somewhat confused on the meaning of translationese. The wiki defines it as an overly literal translation, but the code [here](https://github.com/mjpost/sacreBLEU/pull/43/files) is all about the subset selection, not relative to quantifying the translationese. Did I get something wrong?

**Comment by martinpopel** [comment]
When evaluating e.g. the English->German translation on the `--origlang=de` subset, it means that the source English sentences are manual translations from German, i.e. they are translationese; and the references are original German sentences.
When evaluating on the `--origlang=en` subset, it is the other way round: original English source sentences and translationese German references.

> The wiki defines it as an overly literal translation

I understand *translationese* as a general term for a language which is translated from another language. Citing [my thesis](http://ufal.mff.cuni.cz/~popel/papers/phd_thesis.pdf#page=40):

Translationese is a term used in translation studies (translatology). A text translated
from language X into Y has different properties (lexical choice, syntactic
structure, etc.) than a text originally written in language Y [Gellerstam, 1986,
Koppel and Ordan, 2011]. Some scholars [e.g. Toury, 1995] consider the former
(X-specific translationese of Y) a dialect of the latter (original Y). Some [e.g. Baker
et al., 1993] emphasize general properties of translationese, which are independent
of the source language X.

Translationese sometimes denotes rather **negative aspects** of translations
which should be avoided by professional translators. Sometimes it denotes
**neutral or even positive aspects** of translated language, for example localization
or preserving ambiguities of the source language also in the target language if
there is not enough context to resolve the ambiguity.

**Comment by andyweizhao** [comment]
Thank you very much for the helpful explanation!

**Comment by ozancaglayan** [comment]
Can this be closed?
