### ISSUE TITLE
sentence_bleu return type change

### ISSUE THREAD

**Issue by tdomhan** [mjpost/sacreBLEU#53]
Quick question:

since this PR:
https://github.com/mjpost/sacreBLEU/commit/061175ec673ff5f43b780074369219192dbf80b0

`sentence_bleu ` no longer returns a float but a `BLEU` object, unlike `sentence_chrf` which returns a float. Is this API change intended?

As context this will break the [`Reranker`](https://github.com/awslabs/sockeye/blob/master/sockeye/rerank.py#L34) in Sockeye. We can of course branch around whether BLEU or chrf is used, but before we do this I wanted to check whether this was intended.

**Comment by mjpost** [comment]
Hmm, thanks for pointing this out. This is the result of sacrebleu development moving forward in small steps and me trying not to spend too much time on it. It's useful often to have more than just the score, so ideally both function would return an object. I agree they should return the same type.

Do you have a preference for how to resolve this?

**Comment by tdomhan** [comment]
Makes sense. How about returning an object (same or different) but in both cases having a `.score` attribute? This way we expose more information plus one can just call `sentence_*(...).score` if the float is all that one is interested in.

**Comment by mjpost** [comment]
Can I ask you for a code review on #54?

**Comment by mjpost** [comment]
I just released v1.4.2.
