### ISSUE TITLE
Smoothing method add-k is called add-n in argparse, will never be executed

### ISSUE THREAD

**Issue by villmow** [mjpost/sacrebleu#65]
Hi, 

when creating the argument parser one has the following choices for smoothing methods: 
https://github.com/mjpost/sacreBLEU/blob/326c43b8d1bdf2ae9183116e7525933ff36b82a9/sacrebleu.py#L1622

However, the smoothing method `add-n` is called `add-k` in the remainder of the code and thus will never be executed:
https://github.com/mjpost/sacreBLEU/blob/326c43b8d1bdf2ae9183116e7525933ff36b82a9/sacrebleu.py#L1304

**Comment by martinpopel** [comment]
Should be fixed by merging #55.

**Comment by mjpost** [comment]
Thanks for reporting, @villmow!
