### ISSUE TITLE
v1.4.6 broke some imports

### ISSUE THREAD

**Issue by tholiao** [mjpost/sacrebleu#71]
Previously, I relied on being able to import `DATASETS`, `SACREBLEU_DIR`, `_clean`, and `smart_open` from sacrebleu. The refactor in #66 (9baed3e) broke the latter three imports. 

While I admit that relying on underscore function imports is hacky, I think `SACREBLEU_DIR` is clearly something that should be importable. The case of `smart_open` is more ambiguous: there is a reasonable argument to be made for keeping it "under the hood", and the code is trivial to duplicate, but the backwards incompatibility is both a severe and unexpected change.

**Comment by mjpost** [comment]
Fixed in #029e39edfb733a524d7ea4fc7f64fa93e81b9f53 (1.4.6).
