### ISSUE TITLE
Error caused by mecab-python3

### ISSUE THREAD

**Issue by mjpost** [mjpost/sacrebleu#74]
> I get an error trying to 
> pip install sacrebleu
>
> I wonder whether it is this commit that now prevents me from installing sacrebleu on Windows either in the system install or in Anaconda.
> Here's the main part of the error:

```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\David\AppData\Local\Temp\pip-record-qbdi82e5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\Include\mecab-python3'
         cwd: C:\Users\David\AppData\Local\Temp\pip-install-7ez0vltn\mecab-python3\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\MeCab
    copying src\MeCab\__init__.py -> build\lib.win-amd64-3.7\MeCab
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------

> ERROR: Command errored out with exit status 1: 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\David\AppData\Local\Temp\pip-record-qbdi82e5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\Include\mecab-python3' Check the logs for full command output.
```

> I don't think that this is the fault of Sacrebleu though - I can't find a way to install mecab-python3 on my machine at all.  I need a 64 bit python since it is required by TensorFlow that is required by OpenNMT-tf.  The site for Mecab says that it is only available on 32bit Python.  So if that's the case has this change prevented the use of "pip install sacrebleu" on all 64bit python installations?
>
> _Originally posted by @davidbaines in https://github.com/mjpost/sacrebleu/pull/61#issuecomment-616145209_

**Comment by mjpost** [comment]
A temporary workaround is to force install an older version:

```
pip3 install sacrebleu==1.4.4
```

But clearly this is an issue. I don't have a Windows machine to test on, but have not had a problem testing this on 64-bit Linux platforms. Maybe @emjotde could comment?

If this does turn out to be a problem, I wonder if we could (a) remove mecab from the list of required modules and (b) have sacrebleu print a warning about manually installing it if someone tries to use `-tok ja-mecab`.

**Comment by MorinoseiMorizo** [comment]
Hi,
I have created the PR that adds a Japanese tokenizer, and I have not checked it fully work on Windows because I don't have a machine to test.
I'm sorry about that.

@mjpost I think that is a nice suggestion. If you don't have time to fix it, I may create another PR.

**Comment by emjotde** [comment]
For Windows, are we talking WSL here?

**Comment by davidbaines** [comment]
> For Windows, are we talking WSL here?

No this is just Python on Windows. The error occurs in a command window. I haven't tried it in Powershell.

**Comment by mjpost** [comment]
@MorinoseiMorizo if you have time to create a PR to handle this for Windows, that would be great. But don't feel bad—I think it's most important that it works on Unix (which it does).

**Comment by MorinoseiMorizo** [comment]
@mjpost Sure, I will send a PR ASAP. Now I have a Windows machine that can be used for testing.

**Comment by mjpost** [comment]
This should be fixed as of bcfdd0368e72f15308509b49ad471497d3dc0e2a and release version 1.4.9.

**Comment by gvskalyan** [comment]
@mjpost passing `--tok ja-mecab` fails due to [this](https://github.com/mjpost/sacrebleu/blob/bcfdd0368e72f15308509b49ad471497d3dc0e2a/sacrebleu/tokenizer.py#L263) line .
```AttributeError: 'TokenizeMeCab' object has no attribute 'tagger'```
Since tagger has been removed from init

**Comment by mjpost** [comment]
Ah, that’s why. Someone had run into this and I couldn’t reproduce it. It must be because I was using `-b` which disables the signature.
