### ISSUE TITLE
Porting sacrebleu to linux package manager(s)

### ISSUE THREAD

**Issue by atreyasha** [mjpost/sacrebleu#83]
Hello, thank you very much for developing this package, it is super useful!

I noticed that `sacrebleu` has 46 releases currently and probably has a fast development rate. I was wondering if you might be interested in porting `sacrebleu` into user-based linux package repositories (on top of pip). Compared to installing/updating separately with `pip`, this would make keeping everything up-to-date much easier by simply using your standard package manager.

If this is of interest, I would be glad to port `sacrebleu` into the Arch Linux User Repository (AUR) [here](https://aur.archlinux.org/). I can also make a PR to add some scripts that will keep this updated every time there is a new release on your repository.

**Comment by mjpost** [comment]
I don't know what this would involve, but I'd be happy to review a PR.

**Comment by atreyasha** [comment]
Awesome. I would have to create a package for `sacrebleu` on the AUR platform. I will write a (shell) script that can be executed every time there is a new release of this package, and this script will essentially push the update to the AUR (just like a sync).

As I am a bit occupied at the moment, I would only be able to do this later on. Will keep you posted on any updates.

**Comment by ozancaglayan** [comment]
Feel free to send the relevant PR when ready, closing this issue. Thanks!
