### ISSUE TITLE
refactor tokenization classes

### ISSUE THREAD

**Issue by mjpost** [mjpost/sacrebleu#85]
Tokenization is all hacked together with a dictionary of functions. This has caused problems with the Mecab tokenizer. It would be good to factor this out into a simple class hierarchy.

**Comment by ozancaglayan** [comment]
I started working on this. If you did not do anything so far, you can assign this to me.

**Comment by mjpost** [comment]
Sounds great—thanks, Ozan.

**Comment by ozancaglayan** [comment]
FYI, I also refactored out metrics into their own classes with proper formatters and signature providers. I'll keep pushing onto this branch but I don't know if you'll be willing to accept all of these major refactorings.

**Comment by ozancaglayan** [comment]
Comparing results of sacrebleu and chrF++, I noticed that sacrebleu does not implement the word order parameter and the out-of-the-box numbers produced by the two scripts are rather different unless I pass `-nw 0` to chrF++. Was it OK to implement the metric like this?

**Comment by m-popovic** [comment]
Ah, yes, chrF++ by default takes into account n-grams with 6 characters + 2 words. Pure chrf therefore requires to set -nw 0  (nw = word n-gram order).

**Comment by ozancaglayan** [comment]
Oh so chrF and chrF++ are actually two different metrics then. Thanks!
