### ISSUE TITLE
Crashes when run without installation

### ISSUE THREAD

**Issue by emjotde** [mjpost/sacrebleu#86]
Hi,
Used to be possible to run `sacrebleu` directly from the cloned folder like:

```
git clone https://github.com/mjpost/sacrebleu
./sacrebleu/sacrebleu/sacrebleu.py -h
```

This dies now with:
```
Traceback (most recent call last):
  File "./sacrebleu/sacrebleu/sacrebleu.py", line 41, in <module>
    from .tokenizer import TOKENIZERS, TokenizeMeCab
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by mjpost** [comment]
Does `python -m sacrebleu` work (from the sacrebleu root dir)?

**Comment by emjotde** [comment]
Yep, that works.

**Comment by mjpost** [comment]
It was already there :) In your defense, I did break backward compatibility.

**Comment by emjotde** [comment]
Ah, but I meant it could be run from anywhere. Sorry, that was unclear. So any relative path would work before.

**Comment by mjpost** [comment]
So, I think you are asking for a CLI script that you don't need to be in the directory to run?

**Comment by emjotde** [comment]
yes, that worked like here:
https://github.com/marian-nmt/marian-examples/blob/c19b7814d71febf1053bd93af6ac314b46204092/training-basics-sentencepiece/run-me.sh

If you don't want to support that then OK. I just assumed it's a regression.

**Comment by cfedermann** [comment]
Instead of running:

    ./sacrebleu/sacrebleu/sacrebleu.py -h

run it like this:

    python -m sacrebleu.sacrebleu ./sacrebleu/sacrebleu/sacrebleu.py -h

If you know the absolute path, use `PYTHONPATH`:

    PYTHONPATH=/path/to/sacrebleu python -m sacrebleu.sacrebleu /path/to/sacrebleu/sacrebleu/sacrebleu.py -h

**Comment by emjotde** [comment]
I am sure we can come up with a version that mentions the module path more than just three times :)

**Comment by mjpost** [comment]
It’s like the opposite of the Obfuscated Perl contests—call it Prolix Python. 

I am not sure if Python allows a “sacrebleu.py” in the root dir but let me see what I can do.

**Comment by emjotde** [comment]
Thanks! Christian's solution reminds me of the darks times when I last had to use java and CLASSPATH some 20(?) years ago.

**Comment by ozancaglayan** [comment]
This also works for me: `PYTHONPATH=/path/to/sacrebleu python -m sacrebleu.sacrebleu` which is not that bad?

**Comment by ozancaglayan** [comment]
This also seems to work when added on top of `sacrebleu.py` if you are still interested and want to test it @emjotde 
```
+import pathlib
 
+if __name__ == '__main__' and  __package__ is None:
+    parent = pathlib.Path(__file__).absolute().parents[1]
+    sys.path.insert(0, str(parent))
+    __package__ = 'sacrebleu'
```

**Comment by mjpost** [comment]
@ozancaglayan are you saying that we could add a top-level `sacrebleu.py` that would (a) allow the library to load correctly and (b) allow the use of a command-line `sacrebleu.py`? If so, that would be great. I think the use Marcin wants is to be able to type:

```bash
/path/to/sacrebleu/sacrebleu.py
```

**Comment by ozancaglayan** [comment]
if you just add those lines on top of the sacrebleu.py right before
relative imports, full path call worked for me. I also tried invoking the
script after installing, and it was working as well.

**Comment by mjpost** [comment]
Shall we add this to #88 and close this issue then, too?

**Comment by ozancaglayan** [comment]
Possible but I am not sure if that can break some use of the library as a
library and/or as a CLI. I'll add it, you'll merge and maybe you and Marcin
can test in your own envs before doing the release?

**Comment by mjpost** [comment]
Let me merge #88 first so we have a stable release. We could test this next then.

**Comment by ozancaglayan** [comment]
@emjotde can you test the fix if you find some time?
