### ISSUE TITLE
Using own test set data

### ISSUE THREAD

**Issue by JustCunn** [mjpost/sacrebleu#92]
Apologies if this is a really simple question. I am doing an NMT project for a student science exhibition. I am trying to debug a high BLEU score problem I have (calculated by Fairseq).

I have my own dev set with my decoder's predictions too. My language pair (en-ga [Irish]) is not available in any of the pre-processed sets. How may I use my own material with sacrebleu? I only ask because I find the readme just a small bit unclear on that (unless I'm missing something).

Thanks.

**Comment by martinpopel** [comment]
There is no registered (WMT) test set for Irish in SacreBLEU, but you can provide the reference filename (REF1) as an argument on the command line (and omit the `-t` and `-l` parameters). The README shows this alternative usage with an example
```
cat output.detok.txt | sacrebleu REF1 [REF2 ...]
```

**Comment by JustCunn** [comment]
My bad, it was right there all along. Thanks for that!
