### ISSUE TITLE
Compatibility Issue w/ mecab-python3==1.0.0

### ISSUE THREAD

**Issue by pks** [mjpost/sacrebleu#94]
I get the following error when using `sacrebleu==1.4.10` with `-tok ja-mecab` and `mecab-python3==1.0.0`:

```
Failed when trying to initialize MeCab. Some things to check:

    - If you are not using a wheel, do you have mecab installed?

    - Do you have a dictionary installed? If not do this:

        pip install unidic-lite

    - If on Windows make sure you have this installed:

        https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

    - Try creating a Model with the same arguments as your Tagger; that may
      give a more descriptive error message.

If you are still having trouble, please file an issue here:

    https://github.com/SamuraiT/mecab-python3/issues
Traceback (most recent call last):
  File "env/bin/sacrebleu", line 8, in <module>
    sys.exit(main())
  File "env/lib/python3.5/site-packages/sacrebleu/sacrebleu.py", line 1003, in main
    bleu = corpus_bleu(system, refs, smooth_method=args.smooth, smooth_value=args.smooth_value, force=args.force, lowercase=args.lc, tokenize=args.tokenize)
  File "env/lib/python3.5/site-packages/sacrebleu/sacrebleu.py", line 637, in corpus_bleu
    output, *refs = [TOKENIZERS[tokenize](x.rstrip()) for x in lines]
  File "env/lib/python3.5/site-packages/sacrebleu/sacrebleu.py", line 637, in <listcomp>
    output, *refs = [TOKENIZERS[tokenize](x.rstrip()) for x in lines]
  File "env/lib/python3.5/site-packages/sacrebleu/tokenizer.py", line 253, in tokenize
    self.load()
  File "env/lib/python3.5/site-packages/sacrebleu/tokenizer.py", line 239, in load
    self.tagger = MeCab.Tagger("-Owakati")
  File "env/lib/python3.5/site-packages/MeCab/__init__.py", line 105, in __init__
    super(Tagger, self).__init__(args)
RuntimeError
```

Installing `unidic-lite` results in a failing assertion:
```
Traceback (most recent call last):
  File "env/bin/sacrebleu", line 8, in <module>
    sys.exit(main())
  File "env/lib/python3.5/site-packages/sacrebleu/sacrebleu.py", line 1003, in main
    bleu = corpus_bleu(system, refs, smooth_method=args.smooth, smooth_value=args.smooth_value, force=args.force, lowercase=args.lc, tokenize=args.tokenize)
  File "env/lib/python3.5/site-packages/sacrebleu/sacrebleu.py", line 637, in corpus_bleu
    output, *refs = [TOKENIZERS[tokenize](x.rstrip()) for x in lines]
  File "env/lib/python3.5/site-packages/sacrebleu/sacrebleu.py", line 637, in <listcomp>
    output, *refs = [TOKENIZERS[tokenize](x.rstrip()) for x in lines]
  File "env/lib/python3.5/site-packages/sacrebleu/tokenizer.py", line 253, in tokenize
    self.load()
  File "env/lib/python3.5/site-packages/sacrebleu/tokenizer.py", line 242, in load
    assert d.size == 392126, "Please make sure to use IPA dictionary for MeCab"
AssertionError: Please make sure to use IPA dictionary for MeCab
```

With `mecab-python3==0.996.5` it works just fine.

**Comment by ozancaglayan** [comment]
It seems that they now depend on an external dictionary package but I am not very familiar with mecab internals. There's an upstream issue https://github.com/SamuraiT/mecab-python3/issues/47

But for me, installing `unidic-lite` seems to fix the issue.

**Comment by ozancaglayan** [comment]
Please see https://github.com/SamuraiT/mecab-python3/issues/47#issuecomment-653000913
In short, the new version requires `unidic-lite` dictionary to be installed and the use of this dictionary seems to affect final BLEU scores (the unit test goes from 14.5 to 19.6 if I did not do anything stupid) So if the community would like to stick with the previous numbers, we should add mecab-python3 as a dependency to sacreBLEU and pin the version to 0.996.5 @MorinoseiMorizo @mjpost .

**Comment by pks** [comment]
I get an assertion error when installing `unidic-lite`, since sacrebleu checks for the size of the vocabulary: `assert d.size == 392126`.

**Comment by mjpost** [comment]
I suggest in the meantime we require the older version. We could add this to #88.

**Comment by ozancaglayan** [comment]
Can we add this as hard-dep to setup.py?

**Comment by mjpost** [comment]
That’s what I was thinking.

**Comment by MorinoseiMorizo** [comment]
@ozancaglayan 
Thanks for the fix!
I think it is ok to the use previous version of `mecab-python3` in the meantime.

As you noticed, Japanese tokenizer heavily relies on the dictionaries and if the different dictionary used, BLEU scores could be different.
This is one of the major motivation why I wanted to add Japanese to sacreBLEU.

I used the IPA dictionary because it is one of the major dictionaries for Japanese and `mecab-ptyhon3` included the dictionary.
However, the IPA dictionary is not included now and the developer of `mecab-python3` recommends using unidic, so it might be good to discuss what dictionary to be used.
I think we have several options.

1) stick with the older `mecab-python3`.
Pros: comparable with older numbers.
Cons: may not work in the future.

2) change the default dictionary to unidic.
Pros: recommended by the developer of `mecab-python3`.
Cons: scores are not comparable to IPA. Even if we choose this option, we need to pin the dictionary version for a fair comparison.

3) use a different library to tokenize Japanese.
Pros: may solve the dictionary problem.
Cons: I don't know the good alternative.

**Comment by pks** [comment]
There's also the tiny segmenter: https://pypi.org/project/tinysegmenter/

**Comment by pks** [comment]
Thanks!

**Comment by bhavints** [comment]
The downgraded mecab version is failing for me.

**Comment by ozancaglayan** [comment]
Can you please elaborate more? What is the failure?

**Comment by polm** [comment]
I have released a version of ipadic for PyPI, so you can use the old dictionary with the most recent mecab-python3 code, like this:

```
import MeCab
import ipadic
tagger = MeCab.Tagger(ipadic.MECAB_ARGS)
print(tagger.parse("図書館にいた事がバレた"))
```

I think you should look at changing to Unidic as soon as is feasible, but this gives you the option of using the old dictionary with the more recent version of the library for now.

@ozancaglayan I think bhavints was referring to a C++ redistributable required by mecab-python3 on Windows, which is [clearly stated in the README](https://github.com/SamuraiT/mecab-python3#windows-redistributable). mecab-python3 didn't have Windows wheels before 1.0 but could probably be compiled from source, in which case that redistributable might still be required.

**Comment by ykkhan** [comment]
Yes, this error will solve by using mecab-python3==0.996.5 version.
